# Generated by Django 4.0.3 on 2022-03-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('post_data', models.DateTimeField(auto_now_add=True)),
                ('pre_text', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='posts')),
                ('city', models.CharField(max_length=50)),
                ('author', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
    ]
