# Generated by Django 4.0.3 on 2022-03-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
