# Generated by Django 4.0.3 on 2022-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_pre_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
