# Generated by Django 4.0.3 on 2022-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_remove_category_friendly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
